### ISSUE TITLE
Requerir autenticación para operaciones de escritura

### ISSUE THREAD

**Issue by pedrogk** [azubieta/hgathering-api#4]
Eventualmente necesitaremos agregar autenticación a las operaciones de escritura. No urge en este momento porque primero habría que definir quienes van a tener privilegios, pero sí hay que tenerlo en cuenta.

Originalmente se había planteado manejar la autenticación por medio de auth0. Me parece adecuado. ¿Alguien sabe que tan sencillo es meterle auth0 a este api?

**Comment by azubieta** [comment]
desplegarlo sin oauth está bien sencillo

ya con fb y otros es más trabajoso
en este link está como hacerlo para fb
https://strongloop.com/strongblog/loopback-facebook-api-user-authentication/

**Comment by pedrogk** [comment]
Ok. Vamos a comenzar a hacerlo con db storage de user/password en auth0.

**Comment by pedrogk** [comment]
@azubieta puedes trabajarlo o ocupas que alguien más le de?

**Comment by azubieta** [comment]
Ahorita si ando algo ocupado, si hay alguien con conocimientos de nodejs pues que vaya adelantando y luego me hace un pr

**Comment by azubieta** [comment]
hecho
